name: auto_enrollment

on:
  schedule:
  - cron: '45 13 * * 3'

jobs:
  enroll:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Execute script
        run: |
          cd $GITHUB_WORKSPACE
          python asvz_bot.py